---

- name: Get the Kubernetes join command
  command: kubeadm token create --print-join-command
  register: kubeadm_join_command
  delegate_to: "{{ groups['master_node'][0] }}"

- name: Join worker node to Kubernetes cluster
  command: "{{ kubeadm_join_command.stdout }}"
